-- add the JSON SERDE --
ADD JAR /data/w205Project/load/hive-serdes-1.0-SNAPSHOT.jar;

--CLEAN-UP ALLOWS TO RERUN THE SCRIPT
DROP TABLE USERS_TWEETS_ATTRIBUTES;

-- CREATE THE TABLE WITH COLS EXTRACTED FOR FURTHER PROCESSING
-- USE THE RECORD'S CREATED TIMESTAMP TO ONLY LOOK FOR A DAY'S WORTH OF TWEETS
CREATE TABLE USERS_TWEETS_ATTRIBUTES AS
SELECT USER.ID_STR AS USER_ID, ID_STR AS TWEET_ID,
TEXT AS TWEET,
COUNT(split(TEXT,' ')) AS NUM_WORDS,
CURRENT_TIMESTAMP AS CREATED_TS,
USER.CREATED_AT AS USER_CREATED_TS,
CREATED_AT AS TWEET_CREATED_TS,
USER.SCREEN_NAME, USER.NAME,
USER.FOLLOWERS_COUNT AS NUM_FOLLOWING,
USER.FRIENDS_COUNT AS NUM_FOLLOWERS,
USER.STATUSES_COUNT AS NUM_TWEETS,
RETWEETED, RETWEET_COUNT,
COUNT(ENTITIES.URLS) AS NUM_URLS,
COUNT(ENTITIES.USER_MENTIONS) AS NUM_MENTIONS,
COUNT(ENTITIES.HASHTAGS) AS NUM_HASTAGS,
USER.URL AS USER_PROFILE_URL,
ENTITIES.URLS AS TWEETED_URLS
FROM TWEETS WHERE USER.VERIFIED <> TRUE AND RETWEETED_STATUS IS NULL
AND regexp_extract(CREATED_AT, '([0-9][0-9])', 1)-DAY(CURRENT_DATE) = 0
GROUP BY USER.ID_STR, USER.CREATED_AT, USER.URL, USER.NAME, USER.SCREEN_NAME,
USER.FOLLOWERS_COUNT, USER.FRIENDS_COUNT, USER.STATUSES_COUNT, ENTITIES.URLS,
RETWEETED, RETWEET_COUNT, TEXT;