#! bin/bash

# add today's partition
today=$(date +"%Y/%m/%d")
location="/user/flume/tweets/$today"
hive -e "ADD JAR /data/w205Project/load/hive-serdes-1.0-SNAPSHOT.jar; ALTER TABLE tweets ADD IF NOT EXISTS PARTITION (today_date = '$today') location '$location'; select * from tweets limit 1;"

# transform today's partition for processing
hive -e "
ADD JAR /data/w205Project/load/hive-serdes-1.0-SNAPSHOT.jar;
DROP TABLE USERS_TWEETS_ATTRIBUTES;
CREATE TEMPORARY TABLE USERS_TWEETS_ATTRIBUTES AS
SELECT USER.ID_STR AS USER_ID, 
ID_STR AS TWEET_ID,
TEXT AS TWEET,
SIZE(SPLIT(TEXT,' ')) AS NUM_WORDS,
CURRENT_TIMESTAMP AS CREATED_TS,
USER.CREATED_AT AS USER_CREATED_TS,
CREATED_AT AS TWEET_CREATED_TS,
USER.SCREEN_NAME, USER.NAME,
USER.FOLLOWERS_COUNT AS NUM_FOLLOWING,
USER.FRIENDS_COUNT AS NUM_FOLLOWERS,
USER.STATUSES_COUNT AS NUM_TWEETS,
RETWEETED, 
RETWEET_COUNT,
COUNT(ENTITIES.URLS) AS NUM_URLS,
COUNT(ENTITIES.USER_MENTIONS) AS NUM_MENTIONS,
COUNT(ENTITIES.HASHTAGS) AS NUM_HASHTAGS,
USER.URL AS USER_PROFILE_URL,
ENTITIES.URLS AS TWEETED_URLS
FROM TWEETS WHERE USER.VERIFIED <> TRUE AND RETWEETED_STATUS IS NULL
AND today_date='$today'
GROUP BY USER.ID_STR, USER.CREATED_AT, USER.URL, USER.NAME, USER.SCREEN_NAME,
USER.FOLLOWERS_COUNT, USER.FRIENDS_COUNT, USER.STATUSES_COUNT, ENTITIES.URLS,
RETWEETED, RETWEET_COUNT, TEXT;
"

#hive -e "ADD JAR /data/w205Project/load/hive-serdes-1.0-SNAPSHOT.jar;select * from tweets where today_date='$today' limit 1"
#hive -e "ADD JAR /data/w205Project/load/hive-serdes-1.0-SNAPSHOT.jar;select num_words from USERS_TWEETS_ATTRIBUTES limit 10"
#hive -e "ADD JAR /data/w205Project/load/hive-serdes-1.0-SNAPSHOT.jar;select * from USERS_TWEETS_ATTRIBUTES limit 1"
# hive -e "ANALYZE TABLE USERS_TWEETS_ATTRIBUTES COMPUTE STATISTICS noscan;"